// Collect the derivation comment at the top of each plant file into
// src/generated/models.js, shown as "Equations of motion" in the Plant tab.
import fs from 'node:fs';
import path from 'node:path';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const dir = path.join(root, 'src/plants');
const out = {};
for (const f of fs.readdirSync(dir).sort()) {
  if (!f.endsWith('.js') || f === 'index.js' || f === 'common.js') continue;
  const lines = fs.readFileSync(path.join(dir, f), 'utf8').split('\n');
  const head = [];
  for (const l of lines) {
    if (!l.startsWith('//')) break;
    head.push(l.replace(/^\/\/ ?/, ''));
  }
  const id = f.replace(/\.js$/, '');
  if (head.length) out[id] = head.join('\n');
}
fs.mkdirSync(path.join(root, 'src/generated'), { recursive: true });
fs.writeFileSync(path.join(root, 'src/generated/models.js'), '// generated by tools/gen-models.mjs\nexport default ' + JSON.stringify(out, null, 1) + ';\n');
console.log('models:', Object.keys(out).length);
